function [file_name1] = DAP_DAFF(MPS, Theta, Phi, Frequency, theta_step, phi_step, beam_ang, beam_wid)
    addpath( 'C:\Users\Administrator\Documents\RoomSimulation\SourceBeamCtrl\beamformer\functions' ) % Find daffv17_write and daffv17_add_metadata function
    DAP_sampling_rate = 48e3;
    DAP_speed_of_sound = 343.0; % m/s
    DAP_measurement_distance = 10; % m
    DAP_delay_samples = DAP_sampling_rate * DAP_measurement_distance / DAP_speed_of_sound;

    DAP_MPS_userdata = struct();
    DAP_MPS_userdata.samplerate = DAP_sampling_rate;
    DAP_MPS_userdata.MPS = MPS;
    DAP_MPS_userdata.Frequency = Frequency;
    DAP_MPS_userdata.Phi = Phi;
    DAP_MPS_userdata.Theta = Theta;
    DAP_MPS_userdata.Peak = max( abs( MPS ), [], 'all' );
    DAP_MPS_userdata.Scale = true;
    DAP_MPS_userdata.NormalizeFront = false;
    
    dataset = daffv15_create_dataset('alphares', theta_step, ...
                              'betares', phi_step, ...
                              'channels', 1);
    dataset.samplerate = DAP_sampling_rate;
    dataset.metadata = [];
    dataset.metadata = daffv15_metadata_addKey( dataset.metadata, 'Description', 'String', 'DAP' );
    dataset.metadata = daffv15_metadata_addKey( dataset.metadata, 'Creation date', 'String', date );
    dataset.metadata = daffv15_metadata_addKey( dataset.metadata, 'measurement_distance', 'Float', DAP_measurement_distance );
    dataset.metadata = daffv15_metadata_addKey( dataset.metadata, 'delay_samples', 'Float', DAP_delay_samples );
    
    for i=1:dataset.numrecords
        record = dataset.records{i};
        [freqs, mags, metadata] = df_BRAS_directivity_ms(record.alpha, record.beta, DAP_MPS_userdata);
        dataset.records{i}.data = mags;
    end
    
%     % @todo correct!
%     DAP_metadata_base = [];
%     DAP_metadata_base = daffv17_add_metadata( DAP_metadata_base, 'Description', 'String', 'DAP' );
%     DAP_metadata_base = daffv17_add_metadata( DAP_metadata_base, 'Creation date', 'String', date );
%     % DAP_metadata_base = daffv17_add_metadata( DAP_metadata_base, 'License', 'String', 'CC BY-NC 4.0' );
%     % DAP_metadata_base = daffv17_add_metadata( DAP_metadata_base, 'CC License Deed', 'String', 'https://creativecommons.org/licenses/by-nc/4.0/' );
%     % DAP_metadata_base = daffv17_add_metadata( DAP_metadata_base, 'Generation script', 'String', 'Opendaff-v1.7/matlab/directivities/BRAS/BRAS_Genelec8020.m' );
%     % DAP_metadata_base = daffv17_add_metadata( DAP_metadata_base, 'Web Resource (2016)', 'String', 'https://depositonce.tu-berlin.de/handle/11303/7506.2' );
%     DAP_metadata_base = daffv17_add_metadata( DAP_metadata_base, 'measurement_distance', 'Float', DAP_measurement_distance );
%     DAP_metadata_base = daffv17_add_metadata( DAP_metadata_base, 'delay_samples', 'Float', DAP_delay_samples );
    
    %% Magnitude & Phase spectrum
    file_name = ['C:\ITASoftware\Raven\RavenDatabase\DirectivityDatabase\DAP_2022_',num2str(theta_step),'x',num2str(phi_step),'_STEER',num2str(beam_ang - 180),'_wid',num2str(round(beam_wid / 2)),'.ms.daff'];
    file_name1 = ['DAP_2022_',num2str(theta_step),'x',num2str(phi_step),'_STEER',num2str(beam_ang - 180),'_wid',num2str(round(beam_wid / 2)),'.ms.daff'];
    
    
    % daffv17_write( 'filename', 'DAP_2022_1x1_STEER10.ms.daff', ...
    %                 'datafunc', @df_BRAS_directivity_ms, ...
    %                 'userdata', DAP_MPS_userdata, ...
    %                 'metadata', DAP_metadata_base, ...
    %                 'content', 'ms', ...
    %                 'alphares', 1, ...
    %                 'betares', 1, ...
    %                 'orient', [ 0 -90 0 ], ...
    %                 'channels', 1, ...
    %                 'quantization', 'float32' );

%     daffv17_write( 'filename', 'DAP_2022_1x1_STEER10.ms.daff', ...
%                     'datafunc', @df_BRAS_directivity_ms, ...
%                     'userdata', DAP_MPS_userdata, ...
%                     'metadata', DAP_metadata_base, ...
%                     'content', 'ms', ...
%                     'alphares', 1, ...
%                     'betares', 1, ...
%                     'orient', [ 0 0 0 ], ...
%                     'channels', 1, ...
%                     'quantization', 'float32' );
%     daffv17_write( 'filename', file_name, ...
%                     'datafunc', @df_BRAS_directivity_ms, ...
%                     'userdata', DAP_MPS_userdata, ...
%                     'metadata', DAP_metadata_base, ...
%                     'content', 'ms', ...
%                     'alphares', 1, ...
%                     'betares', 1, ...
%                     'orient', [ 0 0 0 ], ...
%                     'channels', 1, ...
%                     'quantization', 'float32' );
    daffv15_write( 'filename', file_name, ...
                    'dataset', dataset, ...
                    'content', 'ms', ...
                    'orient', [ 0 0 0 ], ...
                    'quantization', 'float32',...
                    'freqs', Frequency);

% 
%     
    
end

